/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.CCheckInOutDAO;
import Clases.ItemCombo;
import javax.swing.JOptionPane;
import Clases.ItemCombo;
import Clases.CUsuario;

public class FormCheckInOut extends javax.swing.JFrame {

    private CUsuario usuarioActual;

    private int idReservaSeleccionada = 0;

    public FormCheckInOut() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Check-in / Check-out");

        txtHuespedCheck.setEditable(false);
        txtIdHabitacionCheck.setEditable(false);
        txtFechaCheckIn.setEditable(false);
        txtFechaCheckOut.setEditable(false);
        txtEstadoReservaCheck.setEditable(false);

        CCheckInOutDAO dao = new CCheckInOutDAO();
        dao.cargarReservas(cbReservaCheck);
        dao.mostrarReservasCheck(tbReservasCheck);
    }

    public FormCheckInOut(CUsuario usuario) {
        this();
        this.usuarioActual = usuario;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbReservaCheck = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtHuespedCheck = new javax.swing.JTextField();
        txtIdHabitacionCheck = new javax.swing.JTextField();
        txtFechaCheckIn = new javax.swing.JTextField();
        txtFechaCheckOut = new javax.swing.JTextField();
        txtEstadoReservaCheck = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrarCheckIn = new javax.swing.JButton();
        btnRegistrarCheckOut = new javax.swing.JButton();
        btnVolverCheck = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservasCheck = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbReservaCheck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbReservaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReservaCheckActionPerformed(evt);
            }
        });

        jLabel1.setText("Reserva:");

        txtEstadoReservaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoReservaCheckActionPerformed(evt);
            }
        });

        btnRegistrarCheckIn.setText("Check In");
        btnRegistrarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCheckInActionPerformed(evt);
            }
        });

        btnRegistrarCheckOut.setText("Check Out");
        btnRegistrarCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCheckOutActionPerformed(evt);
            }
        });

        btnVolverCheck.setText("Volver");
        btnVolverCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnVolverCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarCheckIn)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCheckOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverCheck)
                .addContainerGap())
        );

        jLabel2.setText("Huésped:");

        jLabel3.setText("Habitación:");

        jLabel4.setText("Fecha Check in:");

        jLabel5.setText("Fecha Check out:");

        jLabel6.setText("Estado de Reserva:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstadoReservaCheck)
                            .addComponent(txtFechaCheckOut)
                            .addComponent(txtFechaCheckIn)
                            .addComponent(txtIdHabitacionCheck)
                            .addComponent(txtHuespedCheck)
                            .addComponent(cbReservaCheck, 0, 120, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(cbReservaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtHuespedCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addComponent(txtIdHabitacionCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFechaCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(txtEstadoReservaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbReservasCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbReservasCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReservasCheckMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbReservasCheck);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCheckInActionPerformed
        // TODO add your handling code here:
        try {
            if (idReservaSeleccionada == 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva de la tabla.");
                return;
            }

            String estado = txtEstadoReservaCheck.getText().trim();

            if (!estado.equalsIgnoreCase("Reservada")) {
                JOptionPane.showMessageDialog(this,
                        "Solo se puede registrar check-in en reservas con estado Reservada.");
                return;
            }

            CCheckInOutDAO dao = new CCheckInOutDAO();

            dao.registrarCheckIn(
                    idReservaSeleccionada,
                    Integer.parseInt(txtIdHabitacionCheck.getText())
            );

            dao.cargarReservas(cbReservaCheck);
            dao.mostrarReservasCheck(tbReservasCheck);

            limpiarCamposCheck();
            idReservaSeleccionada = 0;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar check-in: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarCheckInActionPerformed

    private void btnVolverCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCheckActionPerformed
        // TODO add your handling code here:
        if (usuarioActual != null) {
            MenuPrincipal menu = new MenuPrincipal(usuarioActual);
            menu.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_btnVolverCheckActionPerformed

    private void txtEstadoReservaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoReservaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoReservaCheckActionPerformed

    private void tbReservasCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReservasCheckMouseClicked
        // TODO add your handling code here:
        int fila = tbReservasCheck.getSelectedRow();

        if (fila >= 0) {

            idReservaSeleccionada
                    = Integer.parseInt(tbReservasCheck.getValueAt(fila, 0).toString());

            txtIdHabitacionCheck.setText(
                    tbReservasCheck.getValueAt(fila, 1).toString());

            txtHuespedCheck.setText(
                    tbReservasCheck.getValueAt(fila, 2).toString());

            txtFechaCheckIn.setText(
                    tbReservasCheck.getValueAt(fila, 4).toString());

            txtFechaCheckOut.setText(
                    tbReservasCheck.getValueAt(fila, 5).toString());

            txtEstadoReservaCheck.setText(
                    tbReservasCheck.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_tbReservasCheckMouseClicked

    private void cbReservaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReservaCheckActionPerformed
        // TODO add your handling code here:
        try {
            if (cbReservaCheck.getSelectedItem() != null) {
                ItemCombo reserva = (ItemCombo) cbReservaCheck.getSelectedItem();

                CCheckInOutDAO dao = new CCheckInOutDAO();
                dao.cargarDatosReserva(
                        reserva.getId(),
                        txtHuespedCheck,
                        txtIdHabitacionCheck,
                        txtFechaCheckIn,
                        txtFechaCheckOut,
                        txtEstadoReservaCheck
                );
            }
        } catch (Exception e) {
            // Evita errores mientras se está cargando el combo.
        }
    }//GEN-LAST:event_cbReservaCheckActionPerformed

    private void btnRegistrarCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCheckOutActionPerformed
        // TODO add your handling code here:
        
        try {
            if (idReservaSeleccionada == 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva de la tabla.");
                return;
            }

            String estado = txtEstadoReservaCheck.getText().trim();

            if (!estado.equalsIgnoreCase("En curso")) {
                JOptionPane.showMessageDialog(this,
                        "Solo se puede registrar check-out en reservas con estado En curso.");
                return;
            }

            CCheckInOutDAO dao = new CCheckInOutDAO();

            dao.registrarCheckOut(
                    idReservaSeleccionada,
                    Integer.parseInt(txtIdHabitacionCheck.getText())
            );

            dao.cargarReservas(cbReservaCheck);
            dao.mostrarReservasCheck(tbReservasCheck);

            limpiarCamposCheck();
            idReservaSeleccionada = 0;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar check-out: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCheckInOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCheckInOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCheckInOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCheckInOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCheckInOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCheckIn;
    private javax.swing.JButton btnRegistrarCheckOut;
    private javax.swing.JButton btnVolverCheck;
    private javax.swing.JComboBox<String> cbReservaCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReservasCheck;
    private javax.swing.JTextField txtEstadoReservaCheck;
    private javax.swing.JTextField txtFechaCheckIn;
    private javax.swing.JTextField txtFechaCheckOut;
    private javax.swing.JTextField txtHuespedCheck;
    private javax.swing.JTextField txtIdHabitacionCheck;
    // End of variables declaration//GEN-END:variables
    private void limpiarCamposCheck() {
        txtHuespedCheck.setText("");
        txtIdHabitacionCheck.setText("");
        txtFechaCheckIn.setText("");
        txtFechaCheckOut.setText("");
        txtEstadoReservaCheck.setText("");
    }
   
}
