/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.CPago;
import Clases.CPagoDAO;
import Clases.ItemCombo;
import javax.swing.JOptionPane;
import Clases.CUsuario;

public class FormPagos extends javax.swing.JFrame {

    private CUsuario usuarioActual;

    public FormPagos() {
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrar Pago");

        txtIdPago.setEnabled(false);

        cbMedioPago.removeAllItems();
        cbMedioPago.addItem("Efectivo");
        cbMedioPago.addItem("Tarjeta");
        cbMedioPago.addItem("Transferencia");
        cbMedioPago.addItem("Mercado Pago");

        cbEstadoPago.removeAllItems();
        cbEstadoPago.addItem("Pendiente");
        cbEstadoPago.addItem("Aprobado");
        cbEstadoPago.addItem("Rechazado");

        CPagoDAO dao = new CPagoDAO();
        dao.cargarReservas(cbReservaPago);
        dao.mostrarPagos(tbPagos);
    }

    public FormPagos(CUsuario usuario) {
        this();
        this.usuarioActual = usuario;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdPago = new javax.swing.JTextField();
        cbReservaPago = new javax.swing.JComboBox<>();
        dtFechaPago = new com.toedter.calendar.JDateChooser();
        txtMontoPago = new javax.swing.JTextField();
        cbMedioPago = new javax.swing.JComboBox<>();
        cbEstadoPago = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardarPago = new javax.swing.JButton();
        btnModificarPago = new javax.swing.JButton();
        btnEliminarPago = new javax.swing.JButton();
        btnLimpiarPago = new javax.swing.JButton();
        btnVolverPago = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPagos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPagoActionPerformed(evt);
            }
        });

        cbReservaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMedioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEstadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Id:");

        jLabel2.setText("Reserva:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Monto:");

        jLabel5.setText("Medio:");

        jLabel6.setText("Estado:");

        btnGuardarPago.setText("Guardar");
        btnGuardarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPagoActionPerformed(evt);
            }
        });

        btnModificarPago.setText("Modificar");
        btnModificarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPagoActionPerformed(evt);
            }
        });

        btnEliminarPago.setText("Eliminar");
        btnEliminarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPagoActionPerformed(evt);
            }
        });

        btnLimpiarPago.setText("Limpiar");
        btnLimpiarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPagoActionPerformed(evt);
            }
        });

        btnVolverPago.setText("Volver");
        btnVolverPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarPago, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(btnEliminarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnGuardarPago)
                .addGap(18, 18, 18)
                .addComponent(btnModificarPago)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPago)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnVolverPago)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPago)
                            .addComponent(cbReservaPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtMontoPago)
                            .addComponent(cbMedioPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEstadoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addComponent(cbReservaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addComponent(dtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(cbMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPagosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPagos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPagoActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdPago.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un pago de la tabla.");
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar este pago?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                CPagoDAO dao = new CPagoDAO();

                dao.eliminarPago(Integer.parseInt(txtIdPago.getText()));
                dao.mostrarPagos(tbPagos);

                limpiarCamposPago();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar pago: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarPagoActionPerformed

    private void btnLimpiarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPagoActionPerformed
        // TODO add your handling code here:
        limpiarCamposPago();
    }//GEN-LAST:event_btnLimpiarPagoActionPerformed

    private void txtIdPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPagoActionPerformed

    private void btnGuardarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPagoActionPerformed
        // TODO add your handling code here:
        try {
            ItemCombo reserva = (ItemCombo) cbReservaPago.getSelectedItem();

            if (reserva == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva.");
                return;
            }

            if (dtFechaPago.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de pago.");
                return;
            }

            CPago pago = new CPago();

            pago.setIdReserva(reserva.getId());
            pago.setFechaPago(new java.sql.Date(dtFechaPago.getDate().getTime()));
            pago.setMonto(Double.parseDouble(txtMontoPago.getText()));
            pago.setMedioPago(cbMedioPago.getSelectedItem().toString());
            pago.setEstadoPago(cbEstadoPago.getSelectedItem().toString());

            CPagoDAO dao = new CPagoDAO();
            dao.guardarPago(pago);
            dao.mostrarPagos(tbPagos);

            limpiarCamposPago();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser numérico.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar pago: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarPagoActionPerformed

    private void tbPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPagosMouseClicked
        // TODO add your handling code here:
        int fila = tbPagos.getSelectedRow();

        txtIdPago.setText(tbPagos.getValueAt(fila, 0).toString());

        int idReserva = Integer.parseInt(tbPagos.getValueAt(fila, 1).toString());
        seleccionarItemComboPorId(cbReservaPago, idReserva);

        dtFechaPago.setDate((java.util.Date) tbPagos.getValueAt(fila, 5));
        txtMontoPago.setText(tbPagos.getValueAt(fila, 6).toString());
        cbMedioPago.setSelectedItem(tbPagos.getValueAt(fila, 7).toString());
        cbEstadoPago.setSelectedItem(tbPagos.getValueAt(fila, 8).toString());
    }//GEN-LAST:event_tbPagosMouseClicked

    private void btnModificarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPagoActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdPago.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un pago de la tabla.");
                return;
            }

            ItemCombo reserva = (ItemCombo) cbReservaPago.getSelectedItem();

            CPago pago = new CPago();

            pago.setIdPago(Integer.parseInt(txtIdPago.getText()));
            pago.setIdReserva(reserva.getId());
            pago.setFechaPago(new java.sql.Date(dtFechaPago.getDate().getTime()));
            pago.setMonto(Double.parseDouble(txtMontoPago.getText()));
            pago.setMedioPago(cbMedioPago.getSelectedItem().toString());
            pago.setEstadoPago(cbEstadoPago.getSelectedItem().toString());

            CPagoDAO dao = new CPagoDAO();
            dao.modificarPago(pago);
            dao.mostrarPagos(tbPagos);

            limpiarCamposPago();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser numérico.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar pago: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarPagoActionPerformed

    private void btnVolverPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverPagoActionPerformed
        // TODO add your handling code here:
        if (usuarioActual != null) {
            MenuPrincipal menu = new MenuPrincipal(usuarioActual);
            menu.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_btnVolverPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPago;
    private javax.swing.JButton btnGuardarPago;
    private javax.swing.JButton btnLimpiarPago;
    private javax.swing.JButton btnModificarPago;
    private javax.swing.JButton btnVolverPago;
    private javax.swing.JComboBox<String> cbEstadoPago;
    private javax.swing.JComboBox<String> cbMedioPago;
    private javax.swing.JComboBox<String> cbReservaPago;
    private com.toedter.calendar.JDateChooser dtFechaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPagos;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtMontoPago;
    // End of variables declaration//GEN-END:variables
    
    private void seleccionarItemComboPorId(javax.swing.JComboBox combo, int id) {

        for (int i = 0; i < combo.getItemCount(); i++) {

            ItemCombo item = (ItemCombo) combo.getItemAt(i);

            if (item.getId() == id) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }

    private void limpiarCamposPago() {
    txtIdPago.setText("");
    txtMontoPago.setText("");
    dtFechaPago.setDate(null);

    if (cbReservaPago.getItemCount() > 0) {
        cbReservaPago.setSelectedIndex(0);
    }

    if (cbMedioPago.getItemCount() > 0) {
        cbMedioPago.setSelectedIndex(0);
    }

    if (cbEstadoPago.getItemCount() > 0) {
        cbEstadoPago.setSelectedIndex(0);
    }
}
}
