/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.CHabitacion;
import Clases.CHabitacionDAO;
import Clases.CUsuario;
public class FormHabitaciones extends javax.swing.JFrame {

    private CUsuario usuarioActual;

    /**
     * Creates new form FormHabitaciones
     */
    public FormHabitaciones() {
        initComponents();
        setLocationRelativeTo(null);
    setResizable(false);
    setTitle("Administrar Habitaciones");

    txtIdHabitacion.setEnabled(false);

    cbEstadoHabitacion.removeAllItems();
    cbEstadoHabitacion.addItem("Disponible");
    cbEstadoHabitacion.addItem("Ocupada");
    cbEstadoHabitacion.addItem("Mantenimiento");

    CHabitacionDAO dao = new CHabitacionDAO();
    dao.mostrarHabitaciones(tbHabitacion);
    }

    public FormHabitaciones(CUsuario usuario) {
        this();
        this.usuarioActual = usuario;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdHabitacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipoHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidadHabitacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioHabitacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbEstadoHabitacion = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnGuardarHabitacion = new javax.swing.JButton();
        btnModificarHabitacion = new javax.swing.JButton();
        btnEliminarHabitacion = new javax.swing.JButton();
        btnLimpiarHabitacion = new javax.swing.JButton();
        btnVolverHabitacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHabitacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(234, 540));

        txtIdHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdHabitacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Número:");

        jLabel3.setText("Tipo:");

        txtCapacidadHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadHabitacionActionPerformed(evt);
            }
        });

        jLabel4.setText("Capacidad:");

        jLabel5.setText("Precio:");

        jLabel6.setText("Estado:");

        cbEstadoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEstadoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoHabitacionActionPerformed(evt);
            }
        });

        btnGuardarHabitacion.setText("Guardar");
        btnGuardarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHabitacionActionPerformed(evt);
            }
        });

        btnModificarHabitacion.setText("Modificar");
        btnModificarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarHabitacionActionPerformed(evt);
            }
        });

        btnEliminarHabitacion.setText("Eliminar");
        btnEliminarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabitacionActionPerformed(evt);
            }
        });

        btnLimpiarHabitacion.setText("Limpiar");
        btnLimpiarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarHabitacionActionPerformed(evt);
            }
        });

        btnVolverHabitacion.setText("Volver");
        btnVolverHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnEliminarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnGuardarHabitacion)
                .addGap(18, 18, 18)
                .addComponent(btnModificarHabitacion)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarHabitacion)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnVolverHabitacion)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEstadoHabitacion, 0, 120, Short.MAX_VALUE)
                            .addComponent(txtPrecioHabitacion)
                            .addComponent(txtCapacidadHabitacion)
                            .addComponent(txtTipoHabitacion)
                            .addComponent(txtNumeroHabitacion)
                            .addComponent(txtIdHabitacion))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCapacidadHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecioHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHabitacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHabitacion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoHabitacionActionPerformed

    private void txtIdHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdHabitacionActionPerformed

    private void txtCapacidadHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadHabitacionActionPerformed

    private void btnGuardarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHabitacionActionPerformed
        // TODO add your handling code here:
    CHabitacion habitacion = new CHabitacion();

    habitacion.setNumero(txtNumeroHabitacion.getText());
    habitacion.setTipo(txtTipoHabitacion.getText());
    habitacion.setCapacidad(Integer.parseInt(txtCapacidadHabitacion.getText()));
    habitacion.setPrecio(Double.parseDouble(txtPrecioHabitacion.getText()));
    habitacion.setEstado(cbEstadoHabitacion.getSelectedItem().toString());

    CHabitacionDAO dao = new CHabitacionDAO();
    dao.guardarHabitacion(habitacion);
    dao.mostrarHabitaciones(tbHabitacion);

    limpiarCamposHabitacion();
    }//GEN-LAST:event_btnGuardarHabitacionActionPerformed

    private void btnModificarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHabitacionActionPerformed
        // TODO add your handling code here:
        CHabitacion habitacion = new CHabitacion();

        habitacion.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));
        habitacion.setNumero(txtNumeroHabitacion.getText());
        habitacion.setTipo(txtTipoHabitacion.getText());
        habitacion.setCapacidad(Integer.parseInt(txtCapacidadHabitacion.getText()));
        habitacion.setPrecio(Double.parseDouble(txtPrecioHabitacion.getText()));
        habitacion.setEstado(cbEstadoHabitacion.getSelectedItem().toString());

        CHabitacionDAO dao = new CHabitacionDAO();
        dao.modificarHabitacion(habitacion);
        dao.mostrarHabitaciones(tbHabitacion);

        limpiarCamposHabitacion();
    }//GEN-LAST:event_btnModificarHabitacionActionPerformed

    private void btnEliminarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabitacionActionPerformed
        // TODO add your handling code here:
        int idHabitacion = Integer.parseInt(txtIdHabitacion.getText());

        CHabitacionDAO dao = new CHabitacionDAO();
        dao.eliminarHabitacion(idHabitacion);
        dao.mostrarHabitaciones(tbHabitacion);

        limpiarCamposHabitacion();
    }//GEN-LAST:event_btnEliminarHabitacionActionPerformed

    private void btnLimpiarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHabitacionActionPerformed
        // TODO add your handling code here:
        limpiarCamposHabitacion();
    }//GEN-LAST:event_btnLimpiarHabitacionActionPerformed

    private void btnVolverHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHabitacionActionPerformed
        // TODO add your handling code here:
        if (usuarioActual != null) {
            MenuPrincipal menu = new MenuPrincipal(usuarioActual);
            menu.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_btnVolverHabitacionActionPerformed

    private void tbHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHabitacionMouseClicked
        // TODO add your handling code here:
        int fila = tbHabitacion.getSelectedRow();

        txtIdHabitacion.setText(tbHabitacion.getValueAt(fila, 0).toString());
        txtNumeroHabitacion.setText(tbHabitacion.getValueAt(fila, 1).toString());
        txtTipoHabitacion.setText(tbHabitacion.getValueAt(fila, 2).toString());
        txtCapacidadHabitacion.setText(tbHabitacion.getValueAt(fila, 3).toString());
        txtPrecioHabitacion.setText(tbHabitacion.getValueAt(fila, 4).toString());
        cbEstadoHabitacion.setSelectedItem(tbHabitacion.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tbHabitacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarHabitacion;
    private javax.swing.JButton btnGuardarHabitacion;
    private javax.swing.JButton btnLimpiarHabitacion;
    private javax.swing.JButton btnModificarHabitacion;
    private javax.swing.JButton btnVolverHabitacion;
    private javax.swing.JComboBox<String> cbEstadoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHabitacion;
    private javax.swing.JTextField txtCapacidadHabitacion;
    private javax.swing.JTextField txtIdHabitacion;
    private javax.swing.JTextField txtNumeroHabitacion;
    private javax.swing.JTextField txtPrecioHabitacion;
    private javax.swing.JTextField txtTipoHabitacion;
    // End of variables declaration//GEN-END:variables
private void limpiarCamposHabitacion() {
    txtIdHabitacion.setText("");
    txtNumeroHabitacion.setText("");
    txtTipoHabitacion.setText("");
    txtCapacidadHabitacion.setText("");
    txtPrecioHabitacion.setText("");
    cbEstadoHabitacion.setSelectedIndex(0);
}
}
