package Formularios;

import Clases.CFactura;
import Clases.CFacturaDAO;
import Clases.ItemCombo;
import javax.swing.JOptionPane;
import Clases.CFacturaPDF;
import javax.swing.JOptionPane;
import Clases.CUsuario;

public class FormFacturas extends javax.swing.JFrame {

    private CUsuario usuarioActual;

    public FormFacturas() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Emitir Factura");

        txtIdFactura.setEnabled(false);
        txtImporteTotal.setEnabled(false);

        cbTipoFactura.removeAllItems();
        cbTipoFactura.addItem("Factura A");
        cbTipoFactura.addItem("Factura B");
        cbTipoFactura.addItem("Factura T");

        cbEstadoFactura.removeAllItems();
        cbEstadoFactura.addItem("Emitida");
        cbEstadoFactura.addItem("Anulada");

        CFacturaDAO dao = new CFacturaDAO();
        dao.cargarReservasPagadas(cbReservaFactura);
        dao.mostrarFacturas(tbFacturas);

        btnExportarPdf.setEnabled(false);
    }

    public FormFacturas(CUsuario usuario) {
        this();
        this.usuarioActual = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdFactura = new javax.swing.JTextField();
        cbReservaFactura = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtFechaEmision = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cbTipoFactura = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtImporteTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEstadoFactura = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEmitirFactura = new javax.swing.JButton();
        btnModificarFactura = new javax.swing.JButton();
        btnEliminarFactura = new javax.swing.JButton();
        btnLimpiarFactura = new javax.swing.JButton();
        btnExportarPdf = new javax.swing.JButton();
        btnVolverFactura = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFacturas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(240, 500));

        cbReservaFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbReservaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReservaFacturaActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Reserva:");

        jLabel3.setText("Fecha Emision:");

        cbTipoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Tipo:");

        jLabel5.setText("Importe total:");

        cbEstadoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Estado:");

        btnEmitirFactura.setText("Emitir Factura");
        btnEmitirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirFacturaActionPerformed(evt);
            }
        });

        btnModificarFactura.setText("Modificar Factura");
        btnModificarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFacturaActionPerformed(evt);
            }
        });

        btnEliminarFactura.setText("Eliminar Factura");
        btnEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFacturaActionPerformed(evt);
            }
        });

        btnLimpiarFactura.setText("Limpiar");
        btnLimpiarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFacturaActionPerformed(evt);
            }
        });

        btnExportarPdf.setText("Exportar");
        btnExportarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPdfActionPerformed(evt);
            }
        });

        btnVolverFactura.setText("Volver");
        btnVolverFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmitirFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExportarPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEmitirFactura)
                .addGap(18, 18, 18)
                .addComponent(btnModificarFactura)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarFactura)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarFactura)
                .addGap(18, 18, 18)
                .addComponent(btnExportarPdf)
                .addGap(18, 18, 18)
                .addComponent(btnVolverFactura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbReservaFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEstadoFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtImporteTotal)
                            .addComponent(cbTipoFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtFechaEmision, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtIdFactura))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbReservaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEstadoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFacturas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbReservaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReservaFacturaActionPerformed
        // TODO add your handling code here:
        try {
            if (cbReservaFactura.getSelectedItem() != null) {
                ItemCombo reserva = (ItemCombo) cbReservaFactura.getSelectedItem();

                CFacturaDAO dao = new CFacturaDAO();
                double importe = dao.obtenerImporteReserva(reserva.getId());

                txtImporteTotal.setText(String.valueOf(importe));
            }
        } catch (Exception e) {
            // Evita errores cuando el combo se está cargando.
        }
    }//GEN-LAST:event_cbReservaFacturaActionPerformed

    private void btnEmitirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirFacturaActionPerformed
        // TODO add your handling code here:
        try {
            ItemCombo reserva = (ItemCombo) cbReservaFactura.getSelectedItem();

            if (reserva == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva pagada.");
                return;
            }

            if (dtFechaEmision.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de emisión.");
                return;
            }

            CFactura factura = new CFactura();

            factura.setIdReserva(reserva.getId());
            factura.setFechaEmision(new java.sql.Date(dtFechaEmision.getDate().getTime()));
            factura.setTipoFactura(cbTipoFactura.getSelectedItem().toString());
            factura.setImporteTotal(Double.parseDouble(txtImporteTotal.getText()));
            factura.setEstadoFactura(cbEstadoFactura.getSelectedItem().toString());

            CFacturaDAO dao = new CFacturaDAO();
            dao.emitirFactura(factura);
            dao.mostrarFacturas(tbFacturas);
            dao.cargarReservasPagadas(cbReservaFactura);

            limpiarCamposFactura();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El importe total debe ser numérico.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al emitir factura: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEmitirFacturaActionPerformed

    private void tbFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFacturasMouseClicked
        // TODO add your handling code here:
        int fila = tbFacturas.getSelectedRow();

        txtIdFactura.setText(tbFacturas.getValueAt(fila, 0).toString());

        int idReserva = Integer.parseInt(tbFacturas.getValueAt(fila, 1).toString());
        seleccionarItemComboPorId(cbReservaFactura, idReserva);

        dtFechaEmision.setDate((java.util.Date) tbFacturas.getValueAt(fila, 5));
        cbTipoFactura.setSelectedItem(tbFacturas.getValueAt(fila, 6).toString());
        txtImporteTotal.setText(tbFacturas.getValueAt(fila, 7).toString());
        cbEstadoFactura.setSelectedItem(tbFacturas.getValueAt(fila, 8).toString());

        btnExportarPdf.setEnabled(true);
    }//GEN-LAST:event_tbFacturasMouseClicked

    private void btnModificarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFacturaActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdFactura.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una factura de la tabla.");
                return;
            }

            ItemCombo reserva = (ItemCombo) cbReservaFactura.getSelectedItem();

            CFactura factura = new CFactura();

            factura.setIdFactura(Integer.parseInt(txtIdFactura.getText()));
            factura.setIdReserva(reserva.getId());
            factura.setFechaEmision(new java.sql.Date(dtFechaEmision.getDate().getTime()));
            factura.setTipoFactura(cbTipoFactura.getSelectedItem().toString());
            factura.setImporteTotal(Double.parseDouble(txtImporteTotal.getText()));
            factura.setEstadoFactura(cbEstadoFactura.getSelectedItem().toString());

            CFacturaDAO dao = new CFacturaDAO();
            dao.modificarFactura(factura);
            dao.mostrarFacturas(tbFacturas);
            dao.cargarReservasPagadas(cbReservaFactura);

            limpiarCamposFactura();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar factura: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarFacturaActionPerformed

    private void btnEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFacturaActionPerformed
        // TODO add your handling code here:
        try {
            if (txtIdFactura.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una factura de la tabla.");
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar esta factura?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                CFacturaDAO dao = new CFacturaDAO();

                dao.eliminarFactura(Integer.parseInt(txtIdFactura.getText()));
                dao.mostrarFacturas(tbFacturas);
                dao.cargarReservasPagadas(cbReservaFactura);

                limpiarCamposFactura();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar factura: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarFacturaActionPerformed

    private void btnLimpiarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFacturaActionPerformed
        // TODO add your handling code here:
        limpiarCamposFactura();
    }//GEN-LAST:event_btnLimpiarFacturaActionPerformed

    private void btnVolverFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverFacturaActionPerformed
        // TODO add your handling code here:
        if (usuarioActual != null) {
            MenuPrincipal menu = new MenuPrincipal(usuarioActual);
            menu.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_btnVolverFacturaActionPerformed

    private void btnExportarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPdfActionPerformed
        // TODO add your handling code here:
        if (txtIdFactura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una factura de la tabla.");
            return;
        }

        CFacturaPDF pdf = new CFacturaPDF();
        pdf.exportarFacturaPDF(Integer.parseInt(txtIdFactura.getText()));
    }//GEN-LAST:event_btnExportarPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnEmitirFactura;
    private javax.swing.JButton btnExportarPdf;
    private javax.swing.JButton btnLimpiarFactura;
    private javax.swing.JButton btnModificarFactura;
    private javax.swing.JButton btnVolverFactura;
    private javax.swing.JComboBox<String> cbEstadoFactura;
    private javax.swing.JComboBox<String> cbReservaFactura;
    private javax.swing.JComboBox<String> cbTipoFactura;
    private com.toedter.calendar.JDateChooser dtFechaEmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFacturas;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtImporteTotal;
    // End of variables declaration//GEN-END:variables

    private void seleccionarItemComboPorId(javax.swing.JComboBox combo, int id) {

        for (int i = 0; i < combo.getItemCount(); i++) {
            ItemCombo item = (ItemCombo) combo.getItemAt(i);

            if (item.getId() == id) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }

    private void limpiarCamposFactura() {
        txtIdFactura.setText("");
        txtImporteTotal.setText("");
        dtFechaEmision.setDate(null);

        if (cbReservaFactura.getItemCount() > 0) {
            cbReservaFactura.setSelectedIndex(0);
        }

        if (cbTipoFactura.getItemCount() > 0) {
            cbTipoFactura.setSelectedIndex(0);
        }

        if (cbEstadoFactura.getItemCount() > 0) {
            cbEstadoFactura.setSelectedIndex(0);
        }

        btnExportarPdf.setEnabled(false);
    }
}
